---

- name: check for iptables
  command: "systemctl status iptables"
  register: iptables
  ignore_errors: true
  changed_when: false

- name: disable iptables
  service: 
    name: iptables
    enabled: no
    state: stopped
  when: not (iptables.stderr is search("Unit iptables.service could not be found")) 

- name: enable firewalld
  service: 
    name: firewalld
    enabled: yes
    state: started
  when: servers_fw_enabled

- name: disable firewalld
  service: 
    name: firewalld
    enabled: no
    state: stopped
  when: not servers_fw_enabled
