---

- name: reboot
  shell: sleep 2 && /sbin/shutdown -r now "Rebooting..."
  async: 1
  poll: 0

- name: wait 30 secs mandatory
  pause: 
    seconds: 30

- name: wait for ping response
  local_action: shell ansible -u {{ ansible_user_id }} -m ping {{ inventory_hostname }}
  register: result
  until: result.rc == 0
  retries: 30
  delay: 10

- name: host is back
  shell: uptime
